# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 17:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[
                    django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误!')], verbose_name='手机号码')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(2, '女'), (1, '男')], default=2, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('hometown', models.CharField(blank=True, max_length=50, null=True, verbose_name='家庭地址')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住址')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'mk_users',
            },
        ),
    ]
