# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190123_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketusers',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], default=2, verbose_name='性别'),
        ),
    ]
