# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 20:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Activi_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('Activi_image', models.ImageField(upload_to='activity/%Y%m/%d', verbose_name='活动图片地址')),
                ('Activi_url', models.URLField(max_length=255, verbose_name='活动的url地址')),
            ],
            options={
                'verbose_name': '活动管理',
                'verbose_name_plural': '活动管理',
            },
        ),
        migrations.CreateModel(
            name='ActivityZoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('AZ_name', models.CharField(max_length=50, verbose_name='活动专区名称')),
                ('AZ_intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='活动专区简介')),
                ('AZ_order', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_on_sale', models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=0, verbose_name='是否上线')),
            ],
            options={
                'verbose_name': '活动专区管理',
                'verbose_name_plural': '活动专区管理',
            },
        ),
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='轮播活动')),
                ('img_url', models.ImageField(upload_to='banner/%Y%m/%d', verbose_name='轮播图片地址')),
                ('order', models.SmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '轮播管理',
                'verbose_name_plural': '轮播管理',
            },
        ),
        migrations.CreateModel(
            name='ComClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='分类名称')),
                ('class_intro', models.CharField(blank=True, max_length=255, null=True, verbose_name='分类简介')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'ComClassModel',
            },
        ),
        migrations.CreateModel(
            name='ComSkuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Sku_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='商品名')),
                ('comintro', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='商品简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.PositiveIntegerField(verbose_name='库存')),
                ('sales', models.PositiveIntegerField(verbose_name='销量')),
                ('logo', models.ImageField(upload_to='logo/%Y%m/%d', verbose_name='封面图片')),
                ('is_on_sale', models.BooleanField(choices=[(False, '下架'), (True, '上架')], default=False, verbose_name='是否上架')),
                ('Com_spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ComSkuModel', verbose_name='商品SPU')),
                ('Comclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ComClassModel', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品SKU管理',
                'verbose_name_plural': '商品SKU管理',
            },
        ),
        migrations.CreateModel(
            name='ComSpuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('SPU_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='spu名称')),
                ('SPU_details', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='spu详情')),
            ],
            options={
                'verbose_name': '商品SPU表',
                'verbose_name_plural': '商品SPU表',
                'db_table': 'ComSpuModel',
            },
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img_url', models.ImageField(upload_to='gallery/%Y%m/%d', verbose_name='图集图片地址')),
                ('com_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ComSkuModel', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '商品图集管理',
                'verbose_name_plural': '商品图集管理',
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
            ],
            options={
                'verbose_name': '商品单位',
                'verbose_name_plural': '商品单位',
                'db_table': 'UnitModel',
            },
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='com_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ComSkuModel', verbose_name='商品SKU'),
        ),
        migrations.AddField(
            model_name='activityzonemodel',
            name='com_sku',
            field=models.ManyToManyField(to='commodity.ComSkuModel', verbose_name='商品'),
        ),
    ]
