# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 11:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comskumodel',
            name='Com_spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.ComSpuModel', verbose_name='商品SPU'),
        ),
        migrations.AlterField(
            model_name='comspumodel',
            name='SPU_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='spu详情'),
        ),
    ]
